@LLMModel_HostAddress = http://localhost:5159

POST {{LLMModel_HostAddress}}/message/
Accept: application/json
Content-Type: application/json

{
 "content": "",
  "message_id": "",
  "chat_id": ""
}

###
